# Project: Tugas5_dosen
# Makefile created by Dev-C++ 5.4.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o C:/Users/andri/Downloads/Compressed/kubusbergambar/kubusbergambar/imageloader.o
LINKOBJ  = main.o C:/Users/andri/Downloads/Compressed/kubusbergambar/kubusbergambar/imageloader.o
LIBS     = -L"C:/Dev-Cpp/MinGW32/lib" -static-libstdc++ -static-libgcc -mwindows -lglut32 -lglu32 -lopengl32 -lwinmm -lgdi32
INCS     = -I"C:/Dev-Cpp/MinGW32/include"
CXXINCS  = -I"C:/Dev-Cpp/MinGW32/include"
BIN      = Tugas5_dosen.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) -DGLUT_STATIC
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

C:/Users/andri/Downloads/Compressed/kubusbergambar/kubusbergambar/imageloader.o: C:/Users/andri/Downloads/Compressed/kubusbergambar/kubusbergambar/imageloader.cpp
	$(CPP) -c C:/Users/andri/Downloads/Compressed/kubusbergambar/kubusbergambar/imageloader.cpp -o C:/Users/andri/Downloads/Compressed/kubusbergambar/kubusbergambar/imageloader.o $(CXXFLAGS)
